# Azure pipeline for running Puppeteer script using the FloodRunner API

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: PowerShell@2
    displayName: "Run Puppeteer script"
    inputs:
      filePath: 'floodrunner_upload.ps1'
      arguments: '-apiAccessToken ${ApiAccessToken} -FilePath "floodrunner_landing_page.ts"'
      failOnStderr: true
      pwsh: true
